// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaotheonWebAPI.Contexts;

namespace PaotheonWebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201114023231_Bakery")]
    partial class Bakery
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("postgis")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PaotheonWebAPI.Models.Bakery", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("closeHour")
                        .HasColumnType("integer");

                    b.Property<string>("details")
                        .HasColumnType("text");

                    b.Property<float>("latitude")
                        .HasColumnType("real");

                    b.Property<Point>("location")
                        .HasColumnType("geometry");

                    b.Property<float>("longitude")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int>("openHour")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Bakery");
                });
#pragma warning restore 612, 618
        }
    }
}
